<% def env(a, b); e = ENV["obtvse_#{a}"]; e ? e : b; end %>

title: <%= env :title,     'Codeventure Time' %>
domain: <%= env :domain,   'http://www.wontaeyang.com' %>
name:    <%= env :name,    'Wontae Yang' %>
twitter: <%= env :twitter, 'wontae_yang' %>
github:  <%= env :github,  'wontaeyang'  %>
email:   <%= env :email,   'wontaeyang@gmail.com'  %>
about:   <%= env :about,   'Full Stack Ruby Developer, Architect, Designer, Flatiron Grad, Robot, Data Nerd' %>

# Google Analytics
ga_id:   <%= env :ga,      ''  %>
